### ISSUE TITLE
No metdata/rating written to MP3 files

### ISSUE THREAD

**Issue by nodiscc** [pragma-/vlc-ratings#1]
Hi, I think I hit a case of https://github.com/pragma-/vlc-ratings#caveat-regarding-using-metadata, I have attempted adding ratings to multiple .mp3 files and checked their metadata with `mediainfo` and similar tools. There is no trace of the rating being written to file.

This is confirmed by the fact that when `Use data file` is unchecked in extension settings, my ratings do not persist when I hit `refresh playlist`

Why is VLC unable to add the tag in mp3 files? Editing other metadata (title, artist..) works fine

This extension is promising, thanks!

VLC  3.0.8, Debian GNU/Linux 9

**Comment by MrConkin** [comment]
Also experiencing this issue with mp4. @pragma- are you still maintaining this extension?

**Comment by pragma-** [comment]
At the time that this vlc-ratings extension was made, the LUA support in VLC did not expose any API for updating a file's metadata. I do not know if this is still the case. 

VLC 4.0 was looming on the horizon, or so I thought, and I expected it to have improved LUA support and much more. I fully expected this extension to become redundant with VLC 4.0's improved features.

I have not kept myself up-to-date on VLC's latest changes so I am wholly unaware if the LUA API has added better support for reading/writing a file's metadata. If it has improved, I'd be willing to update this extension.
