### ISSUE TITLE
No rating column available on playlist

### ISSUE THREAD

**Issue by fstarred** [pragma-/vlc-ratings#2]
I'm using VLC under MacOS.

There's no Rating column available on the playlist, even when I right click to any column, it show a list of displayable columns such Date, Language, URI, etc etc.. but no Ratings available.

**Comment by pragma-** [comment]
I do not have any access to MacOS. I am unable to do any troubleshooting for this issue. I wish I could help.

This is what my right-click context menu for the playlist window looks like:

![image](https://i.imgur.com/a70VmAR.png)

**Comment by fstarred** [comment]
Thanks for the support. 👍 
I've reported this behaviour on the [official forum](https://forum.videolan.org/viewtopic.php?f=12&t=157571&sid=fa2044b36adb86542a74357b9d382893).
Therefore, I can mark this issue as closed
