### ISSUE TITLE
Rating Plugin only working in Playlist (Linux)

### ISSUE THREAD

**Issue by ReComplexed** [pragma-/vlc-ratings#3]
On Linux, the Plugin works as expected, but only in the Playlist of VLC. But for example in the "My Music" tab of vlc, the rating column is empty, and when i try and rate a playing music file in the same tab, nothing happens.

**Comment by pragma-** [comment]
This seems to be a limitation with VLC's LUA interface. The API does not seem to provide a way to manipulate entries in the "My Music" tab. I've double-checked https://vlc.verg.ca/ and https://code.videolan.org/videolan/vlc/-/tree/master/share/lua. Passing anything other than `"playlist"` to `vlc.playlist.get()` yields `nil` for me.

**Comment by ReComplexed** [comment]
The thing is, the Plugin knows what song is played and shows it correctly
in the rating window. But if I try to rate, it does not write anything to
the rating file, although it knows what audio file is played.

Also another question: Why does your Plugin automatically Pause music when
the rating window is opened?

Pragmatic Software ***@***.***> schrieb am So., 5. Feb. 2023,
22:31:

**Comment by pragma-** [comment]
That's just been the way I use my rating plugin. I open the plugin when I open VLC and I leave it open until I'm done.

Feel free to edit the plugin to behave the way you prefer.
